ALTER TABLE alerts ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'new';
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS assigned_to TEXT NULL;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS model_version TEXT NULL;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS malicious_probability DOUBLE PRECISION NULL;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS contributors_json TEXT NULL;

CREATE TABLE IF NOT EXISTS alert_notes (
  id BIGSERIAL PRIMARY KEY,
  alert_id BIGINT NOT NULL REFERENCES alerts(id) ON DELETE CASCADE,
  author TEXT NOT NULL,
  note TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alert_notes_alert_id ON alert_notes(alert_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(status);
